import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import  './css/style.css'
import { ToastContainer } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';

const poppins = Poppins({subsets: ['latin'], weight: ['300', '400', '500', '600', '700', '800',] });

export const metadata: Metadata = {
  title: "Gram Bazar",
  description: "Generated by Gram Bazar",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <meta name="viewport" content="initial-scale=1, width=device-width" />
      <body className={`${poppins.className} bg-[#fff9f6]`}>
        {children}
        <ToastContainer />
      </body>
    </html>
  );
}
