import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import  './css/style.css'

const poppins = Poppins({subsets: ['latin'], weight: ['300', '400', '500', '600', '700', '800',] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <meta name="viewport" content="initial-scale=1, width=device-width" />
      <body className={`${poppins.className} bg-[#fff9f6]`}>
        {children}
      </body>
    </html>
  );
}
